source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'JotDemo'

platform :ios, '10.0'

def install_pods
  pod "MACH-jot", :path => "../MACH-jot.podspec"
end

target 'JotDemo' do
  install_pods
end

target 'JotDemoTests' do
  install_pods
  pod 'Specta'
  pod 'Expecta'
  pod 'Expecta+Snapshots'
  pod 'OCMockito'
end
